export interface PermissionItem {
  id: string;
  name: string;
  description: string;
}

export interface PermissionCategory {
  id: string;
  name: string;
  description: string;
  permissions: PermissionItem[];
}

export const PERMISSIONS = {
  // Dashboard & Analytics
  VIEW_DASHBOARD: 'dashboard.view',
  VIEW_ANALYTICS: 'analytics.view',
  VIEW_ANALYTICS_ATTENDANCE: 'analytics.attendance',
  VIEW_ANALYTICS_FINANCE: 'analytics.finance',
  VIEW_ANALYTICS_DEMOGRAPHICS: 'analytics.demographics',
  ANALYTICS_REPORT_BUILDER: 'analytics.report-builder',
  ANALYTICS_PREFERENCES: 'analytics.preferences',
  EXPORT_ANALYTICS: 'analytics.export',

  // Activity & Audit Logs
  VIEW_ACTIVITY_LOGS: 'activity-logs.view',
  VIEW_USER_ACTIVITY_LOGS: 'activity-logs.user',
  FILTER_ACTIVITY_LOGS: 'activity-logs.filter',
  EXPORT_ACTIVITY_LOGS: 'activity-logs.export',

  // Member Management
  VIEW_MEMBERS: 'members.view',
  CREATE_MEMBERS: 'members.create',
  EDIT_MEMBERS: 'members.edit',
  DELETE_MEMBERS: 'members.delete',
  IMPORT_MEMBERS: 'members.import',
  EXPORT_MEMBERS: 'members.export',
  VIEW_MEMBER_CONTACT: 'members.contact',
  MANAGE_CONVERTS: 'members.converts',
  MANAGE_FAMILY: 'members.family',
  MANAGE_DOCUMENTS: 'members.documents',
  VIEW_MEMBER_GIVING: 'members.giving',
  VIEW_MEMBER_HISTORY: 'members.history',

  // Attendance Management
  VIEW_ATTENDANCE: 'attendance.view',
  TAKE_ATTENDANCE: 'attendance.take',
  QR_ATTENDANCE: 'attendance.qr',
  VIEW_ATTENDANCE_HISTORY: 'attendance.history',
  VIEW_ATTENDANCE_REPORTS: 'attendance.reports',
  MANAGE_GROUP_ATTENDANCE: 'attendance.groups',
  MANAGE_DEPT_ATTENDANCE: 'attendance.department',
  VIEW_MEMBER_ATTENDANCE: 'attendance.member',
  EDIT_ATTENDANCE: 'attendance.edit',
  DELETE_ATTENDANCE: 'attendance.delete',

  // Groups & Ministries
  VIEW_GROUPS: 'groups.view',
  CREATE_GROUPS: 'groups.create',
  EDIT_GROUPS: 'groups.edit',
  DELETE_GROUPS: 'groups.delete',
  MANAGE_GROUP_CATEGORIES: 'groups.categories',
  MANAGE_GROUP_MEMBERS: 'groups.members',
  MANAGE_GROUP_EVENTS: 'groups.events',
  MANAGE_GROUP_ROLES: 'groups.roles',
  MANAGE_GROUP_ATTENDANCE_RECORDS: 'groups.attendance',
  VIEW_GROUP_REPORTS: 'groups.reports',

  // Departments
  VIEW_DEPARTMENTS: 'departments.view',
  CREATE_DEPARTMENTS: 'departments.create',
  EDIT_DEPARTMENTS: 'departments.edit',
  DELETE_DEPARTMENTS: 'departments.delete',
  MANAGE_DEPT_CATEGORIES: 'departments.categories',
  MANAGE_DEPT_MEMBERS: 'departments.members',
  MANAGE_DEPT_ROLES: 'departments.roles',
  MANAGE_DEPT_MEETINGS: 'departments.meetings',

  // Sunday School
  VIEW_SUNDAY_SCHOOL: 'sunday-school.view',
  VIEW_CLASSES: 'sunday-school.classes.view',
  CREATE_CLASSES: 'sunday-school.classes.create',
  EDIT_CLASSES: 'sunday-school.classes.edit',
  DELETE_CLASSES: 'sunday-school.classes.delete',
  VIEW_STUDENTS: 'sunday-school.students.view',
  MANAGE_STUDENTS: 'sunday-school.students.manage',
  VIEW_TEACHERS: 'sunday-school.teachers.view',
  MANAGE_TEACHERS: 'sunday-school.teachers.manage',
  VIEW_MATERIALS: 'sunday-school.materials.view',
  MANAGE_MATERIALS: 'sunday-school.materials.manage',
  TAKE_CLASS_ATTENDANCE: 'sunday-school.attendance',
  VIEW_SUNDAY_SCHOOL_REPORTS: 'sunday-school.reports',

  // Prayer Requests
  VIEW_PRAYER_REQUESTS: 'prayer-requests.view',
  VIEW_CONFIDENTIAL_PRAYER: 'prayer-requests.view-confidential',
  CREATE_PRAYER_REQUESTS: 'prayer-requests.create',
  EDIT_PRAYER_REQUESTS: 'prayer-requests.edit',
  DELETE_PRAYER_REQUESTS: 'prayer-requests.delete',
  RESPOND_PRAYER_REQUESTS: 'prayer-requests.respond',
  ASSIGN_PRAYER_REQUESTS: 'prayer-requests.assign',
  MANAGE_PRAYER_CATEGORIES: 'prayer-requests.categories',
  UPDATE_PRAYER_STATUS: 'prayer-requests.status',

  // Events Management
  VIEW_EVENTS: 'events.view',
  CREATE_EVENTS: 'events.create',
  EDIT_EVENTS: 'events.edit',
  DELETE_EVENTS: 'events.delete',
  VIEW_CALENDAR: 'events.calendar',
  MANAGE_EVENT_CATEGORIES: 'events.categories',
  MANAGE_EVENT_TEMPLATES: 'events.templates',
  MANAGE_EVENT_REGISTRATIONS: 'events.registrations',
  TRACK_EVENT_ATTENDANCE: 'events.attendance',
  MANAGE_EVENT_GROUPS: 'events.groups',
  BULK_EVENT_ACTIONS: 'events.bulk',
  EXPORT_EVENTS: 'events.export',

  // Financial Management
  VIEW_FINANCE: 'finance.view',
  VIEW_GIVING: 'finance.giving.view',
  MANAGE_GIVING: 'finance.giving.manage',
  MANAGE_GIVING_CATEGORIES: 'finance.giving.categories',
  MANAGE_DONATIONS: 'finance.giving.donations',
  MANAGE_PLEDGES: 'finance.giving.pledges',
  MANAGE_FUNDRAISING: 'finance.giving.fundraising',
  VIEW_GIVING_REPORTS: 'finance.giving.reports',
  VIEW_INCOME: 'finance.income.view',
  CREATE_INCOME: 'finance.income.create',
  EDIT_INCOME: 'finance.income.edit',
  DELETE_INCOME: 'finance.income.delete',
  MANAGE_INCOME_CATEGORIES: 'finance.income.categories',
  VIEW_INCOME_REPORTS: 'finance.income.reports',
  VIEW_EXPENSES: 'finance.expenses.view',
  CREATE_EXPENSES: 'finance.expenses.create',
  EDIT_EXPENSES: 'finance.expenses.edit',
  DELETE_EXPENSES: 'finance.expenses.delete',
  MANAGE_EXPENSE_CATEGORIES: 'finance.expenses.categories',
  VIEW_EXPENSE_REPORTS: 'finance.expenses.reports',
  VIEW_TITHES: 'finance.tithes.view',
  CREATE_TITHES: 'finance.tithes.create',
  EDIT_TITHES: 'finance.tithes.edit',
  DELETE_TITHES: 'finance.tithes.delete',
  MANAGE_TITHE_CATEGORIES: 'finance.tithes.categories',
  VIEW_TITHE_REPORTS: 'finance.tithes.reports',
  VIEW_BUDGETS: 'finance.budgets.view',
  CREATE_BUDGETS: 'finance.budgets.create',
  EDIT_BUDGETS: 'finance.budgets.edit',
  DELETE_BUDGETS: 'finance.budgets.delete',
  MANAGE_BUDGET_CATEGORIES: 'finance.budgets.categories',
  MANAGE_BUDGET_ALLOCATIONS: 'finance.budgets.allocations',
  VIEW_BUDGET_REPORTS: 'finance.budgets.reports',
  VIEW_FINANCIAL_REPORTS: 'finance.reports.view',
  VIEW_ASSET_REPORTS: 'finance.reports.assets',
  VIEW_COMPARISON_REPORTS: 'finance.reports.comparisons',
  EXPORT_FINANCE: 'finance.export',

  // Asset Management
  VIEW_ASSETS: 'assets.view',
  CREATE_ASSETS: 'assets.create',
  EDIT_ASSETS: 'assets.edit',
  DELETE_ASSETS: 'assets.delete',
  MANAGE_ASSET_CATEGORIES: 'assets.categories',
  MANAGE_ASSET_ASSIGNMENT: 'assets.assignment',
  MANAGE_ASSET_MAINTENANCE: 'assets.maintenance',
  VIEW_ASSET_INVENTORY_REPORTS: 'assets.reports',
  EXPORT_ASSETS: 'assets.export',

  // Communications
  VIEW_COMMUNICATIONS: 'communications.view',
  SEND_MESSAGES: 'communications.messages',
  MANAGE_CAMPAIGNS: 'communications.campaigns',
  MANAGE_ANNOUNCEMENTS: 'communications.announcements',
  MANAGE_NEWSLETTERS: 'communications.newsletters',
  MANAGE_MESSAGE_TEMPLATES: 'communications.templates',
  SEND_BROADCASTS: 'communications.send',

  // Settings & System Administration
  VIEW_SETTINGS: 'settings.view',
  MANAGE_CHURCH_PROFILE: 'settings.church-profile',
  VIEW_BRANCHES: 'settings.branches.view',
  CREATE_BRANCHES: 'settings.branches.create',
  EDIT_BRANCHES: 'settings.branches.edit',
  DELETE_BRANCHES: 'settings.branches.delete',
  VIEW_USERS: 'settings.users.view',
  CREATE_USERS: 'settings.users.create',
  EDIT_USERS: 'settings.users.edit',
  DELETE_USERS: 'settings.users.delete',
  SUSPEND_USERS: 'settings.users.suspend',
  VIEW_ROLES: 'settings.roles.view',
  CREATE_ROLES: 'settings.roles.create',
  EDIT_ROLES: 'settings.roles.edit',
  DELETE_ROLES: 'settings.roles.delete',
  MANAGE_PERMISSIONS: 'settings.permissions.manage',
  MANAGE_NOTIFICATIONS: 'settings.notifications',
  MANAGE_INTEGRATIONS: 'settings.integrations',
  MANAGE_BACKUP: 'settings.backup',
  MANAGE_SYSTEM: 'settings.system',

  // User Profile & Account
  VIEW_PROFILE: 'profile.view',
  EDIT_PROFILE: 'profile.edit',
  MANAGE_SECURITY: 'profile.security',
} as const;

export const PERMISSION_CATEGORIES: PermissionCategory[] = [
  {
    id: 'dashboard',
    name: 'Dashboard & Analytics',
    description: 'Dashboard metrics, visual charts, custom reports, and analytics preferences',
    permissions: [
      { id: 'dashboard.view', name: 'View Main Dashboard', description: 'Access main dashboard overview, metrics, and quick action cards' },
      { id: 'analytics.view', name: 'View Analytics Dashboard', description: 'Access high-level analytics, growth trends, and KPI summaries' },
      { id: 'analytics.attendance', name: 'View Attendance Analytics', description: 'Access detailed attendance statistics and service comparison charts' },
      { id: 'analytics.finance', name: 'View Financial Analytics', description: 'Access giving, revenue, and expense analytic trends' },
      { id: 'analytics.demographics', name: 'View Demographics Analytics', description: 'Access member age, gender, and regional distribution insights' },
      { id: 'analytics.report-builder', name: 'Custom Report Builder', description: 'Build and customize custom analytics reports with metrics and filters' },
      { id: 'analytics.preferences', name: 'Manage Analytics Preferences', description: 'Configure custom analytics filters, dashboard widgets, and view settings' },
      { id: 'analytics.export', name: 'Export Analytics Data', description: 'Export charts, analytics metrics, and summary data files' },
    ]
  },
  {
    id: 'activity-logs',
    name: 'Activity & Audit Logs',
    description: 'System audit trails, user access history, and event logs',
    permissions: [
      { id: 'activity-logs.view', name: 'View Activity Logs Directory', description: 'View system audit trails, user logins, and operational action records' },
      { id: 'activity-logs.user', name: 'View User Specific Logs', description: 'Inspect detailed audit logs and activity history for individual users' },
      { id: 'activity-logs.filter', name: 'Filter & Search Logs', description: 'Search logs by module, user, date range, IP address, and action type' },
      { id: 'activity-logs.export', name: 'Export Activity Logs', description: 'Export audit logs to CSV, Excel, or PDF format' },
    ]
  },
  {
    id: 'members',
    name: 'Members & Converts Management',
    description: 'Member directory, profiles, families, converts, and records',
    permissions: [
      { id: 'members.view', name: 'View Members Directory', description: 'View members list and detailed profiles' },
      { id: 'members.create', name: 'Add New Member & Convert', description: 'Register and create new member records or new converts' },
      { id: 'members.edit', name: 'Edit Member Details', description: 'Update member profiles, contact, church details, and personal info' },
      { id: 'members.delete', name: 'Delete Member Records', description: 'Remove member and convert records from the system' },
      { id: 'members.import', name: 'Import Members', description: 'Bulk import member records from CSV or spreadsheet files' },
      { id: 'members.export', name: 'Export Members', description: 'Export member directory lists and datasets to CSV/Excel' },
      { id: 'members.contact', name: 'View Confidential Contact Info', description: 'Access phone numbers, physical residences, and personal contact info' },
      { id: 'members.converts', name: 'Manage Converts & Follow-ups', description: 'Track new converts, assign follow-up mentors, and update milestone stages' },
      { id: 'members.family', name: 'Manage Family Ties', description: 'View family relationships, add relatives, and link members to families' },
      { id: 'members.documents', name: 'Manage Member Documents', description: 'Upload and view membership certificates, IDs, and baptism files' },
      { id: 'members.giving', name: 'View Member Giving History', description: 'Access individual member contribution and tithing statements' },
      { id: 'members.history', name: 'View Member Activity Timeline', description: 'Inspect individual member milestone, attendance, and activity timelines' },
    ]
  },
  {
    id: 'attendance',
    name: 'Attendance Management',
    description: 'Service attendance tracking, QR check-ins, and reports',
    permissions: [
      { id: 'attendance.view', name: 'View Attendance Dashboard', description: 'View attendance overviews, summary cards, and stats' },
      { id: 'attendance.take', name: 'Take Service Attendance', description: 'Mark headcounts and individual attendance for services' },
      { id: 'attendance.qr', name: 'QR Code Check-in & Kiosk', description: 'Use live QR scanner and self-check-in kiosk functionality' },
      { id: 'attendance.history', name: 'View Attendance History', description: 'Browse and inspect past service attendance sessions' },
      { id: 'attendance.reports', name: 'View Attendance Reports', description: 'Generate and analyze attendance trend reports' },
      { id: 'attendance.groups', name: 'Group Attendance', description: 'Record and monitor attendance across small groups and fellowships' },
      { id: 'attendance.department', name: 'Department Attendance', description: 'Track departmental and ministry volunteer attendance records' },
      { id: 'attendance.member', name: 'Member Attendance Records', description: 'Inspect individual member attendance logs and history' },
      { id: 'attendance.edit', name: 'Edit Attendance Records', description: 'Modify and correct recorded attendance numbers' },
      { id: 'attendance.delete', name: 'Delete Attendance Records', description: 'Remove mistaken attendance session records' },
    ]
  },
  {
    id: 'groups',
    name: 'Groups & Ministries',
    description: 'Small groups, fellowships, group members, and events',
    permissions: [
      { id: 'groups.view', name: 'View Groups Directory', description: 'Browse active small groups, fellowships, and group profiles' },
      { id: 'groups.create', name: 'Create New Group', description: 'Add new groups, fellowships, cells, or ministry fellowships' },
      { id: 'groups.edit', name: 'Edit Group Information', description: 'Modify group descriptions, schedules, meeting points, and locations' },
      { id: 'groups.delete', name: 'Delete Groups', description: 'Disband and remove groups from the system' },
      { id: 'groups.categories', name: 'Manage Group Categories', description: 'Create and edit group classifications, types, and tags' },
      { id: 'groups.members', name: 'Manage Group Members', description: 'Add, transfer, and remove members from groups' },
      { id: 'groups.events', name: 'Manage Group Events', description: 'Create and organize group-specific events and meetings' },
      { id: 'groups.roles', name: 'Assign Group Roles', description: 'Designate group leaders, assistants, facilitators, and hosts' },
      { id: 'groups.attendance', name: 'Track Group Attendance', description: 'Record attendance for small group meetings' },
      { id: 'groups.reports', name: 'View Group Reports', description: 'Generate health and attendance reports for small groups' },
    ]
  },
  {
    id: 'departments',
    name: 'Departments Management',
    description: 'Church departments, staff, leadership, and meetings',
    permissions: [
      { id: 'departments.view', name: 'View Departments', description: 'Browse church departments and ministry teams' },
      { id: 'departments.create', name: 'Create Department', description: 'Establish new church departments' },
      { id: 'departments.edit', name: 'Edit Department Information', description: 'Update department goals, budgets, and descriptions' },
      { id: 'departments.delete', name: 'Delete Departments', description: 'Remove inactive departments' },
      { id: 'departments.categories', name: 'Manage Department Categories', description: 'Configure department classifications and structures' },
      { id: 'departments.members', name: 'Manage Department Members', description: 'Assign volunteers and staff to departments' },
      { id: 'departments.roles', name: 'Manage Department Roles', description: 'Designate department heads, coordinators, and roles' },
      { id: 'departments.meetings', name: 'Manage Department Meetings', description: 'Schedule and manage department meetings and minutes' },
    ]
  },
  {
    id: 'sunday-school',
    name: 'Sunday School Management',
    description: 'Classes, student records, teacher assignments, and materials',
    permissions: [
      { id: 'sunday-school.view', name: 'View Sunday School Dashboard', description: 'Access Sunday school overview and class statistics' },
      { id: 'sunday-school.classes.view', name: 'View Classes Directory', description: 'Browse active Sunday school classes and details' },
      { id: 'sunday-school.classes.create', name: 'Create New Class', description: 'Add new age brackets, classes, and departments' },
      { id: 'sunday-school.classes.edit', name: 'Edit Class Details', description: 'Modify class age brackets, rooms, and descriptions' },
      { id: 'sunday-school.classes.delete', name: 'Delete Classes', description: 'Remove Sunday school classes' },
      { id: 'sunday-school.students.view', name: 'View Students Directory', description: 'View enrolled Sunday school students and profiles' },
      { id: 'sunday-school.students.manage', name: 'Manage Student Enrolment', description: 'Enroll, promote, and transfer students between classes' },
      { id: 'sunday-school.teachers.view', name: 'View Teachers Directory', description: 'View Sunday school teacher roster and profiles' },
      { id: 'sunday-school.teachers.manage', name: 'Assign & Manage Teachers', description: 'Assign teachers and assistants to classes' },
      { id: 'sunday-school.materials.view', name: 'Browse Teaching Materials', description: 'Access curriculum, worksheets, lessons, and digital resources' },
      { id: 'sunday-school.materials.manage', name: 'Upload & Manage Materials', description: 'Upload and organize teaching materials and guides' },
      { id: 'sunday-school.attendance', name: 'Record Class Attendance', description: 'Take Sunday school attendance per class session' },
      { id: 'sunday-school.reports', name: 'View Sunday School Reports', description: 'Generate Sunday school growth and attendance reports' },
    ]
  },
  {
    id: 'prayer-requests',
    name: 'Prayer Requests Management',
    description: 'Prayer request submissions, intercession teams, and confidential notes',
    permissions: [
      { id: 'prayer-requests.view', name: 'View Prayer Requests', description: 'Browse and read public prayer requests' },
      { id: 'prayer-requests.view-confidential', name: 'View Confidential Requests', description: 'Access private, sensitive, and pastoral prayer requests' },
      { id: 'prayer-requests.create', name: 'Submit Prayer Request', description: 'Create and log new prayer requests' },
      { id: 'prayer-requests.edit', name: 'Edit Prayer Requests', description: 'Modify prayer request text and details' },
      { id: 'prayer-requests.delete', name: 'Delete Prayer Requests', description: 'Remove resolved or outdated prayer requests' },
      { id: 'prayer-requests.respond', name: 'Respond to Requests', description: 'Add encouraging notes, answers to prayer, and updates' },
      { id: 'prayer-requests.assign', name: 'Assign to Prayer Team', description: 'Delegate requests to specific intercessors and pastoral teams' },
      { id: 'prayer-requests.categories', name: 'Manage Prayer Categories', description: 'Configure prayer request topics and categories' },
      { id: 'prayer-requests.status', name: 'Update Request Status', description: 'Mark requests as praying, answered, or archived' },
    ]
  },
  {
    id: 'events',
    name: 'Events Management',
    description: 'Church events, calendar, registrations, templates, and export',
    permissions: [
      { id: 'events.view', name: 'View Events Directory', description: 'Browse all upcoming and past church events and profiles' },
      { id: 'events.create', name: 'Create New Event', description: 'Schedule and publish new church events' },
      { id: 'events.edit', name: 'Edit Event Details', description: 'Modify dates, locations, speakers, banners, and event info' },
      { id: 'events.delete', name: 'Delete Events', description: 'Cancel and delete events' },
      { id: 'events.calendar', name: 'View Event Calendar', description: 'Access interactive monthly, weekly, and daily event calendars' },
      { id: 'events.categories', name: 'Manage Event Categories', description: 'Configure event categories, departments, and color tags' },
      { id: 'events.templates', name: 'Manage Event Templates', description: 'Create and reuse event scheduling templates' },
      { id: 'events.registrations', name: 'Manage Event Registrations', description: 'Track RSVPs, tickets, and attendee registrations' },
      { id: 'events.attendance', name: 'Track Event Attendance', description: 'Check-in attendees at event entrances' },
      { id: 'events.groups', name: 'Manage Group Event Linkings', description: 'Coordinate small group and ministry participation in events' },
      { id: 'events.bulk', name: 'Execute Bulk Actions', description: 'Perform bulk status updates and attendee notifications' },
      { id: 'events.export', name: 'Export Events Data', description: 'Export event rosters and calendar datasets' },
    ]
  },
  {
    id: 'finance',
    name: 'Finance Management',
    description: 'Giving, donations, income, expenses, tithes, budgets, and statements',
    permissions: [
      { id: 'finance.view', name: 'View Finance Overview', description: 'Access finance dashboard summaries and quick financial stats' },
      { id: 'finance.giving.view', name: 'View Giving & Donations', description: 'Browse giving transactions, donations, and donor records' },
      { id: 'finance.giving.manage', name: 'Record Congregational Giving', description: 'Record Sunday service offering collections' },
      { id: 'finance.giving.categories', name: 'Manage Giving Categories', description: 'Configure funds, special appeals, and giving categories' },
      { id: 'finance.giving.donations', name: 'Manage Donations', description: 'Log and edit general donations and donor receipts' },
      { id: 'finance.giving.pledges', name: 'Manage Pledges', description: 'Track building fund pledges and fulfillment status' },
      { id: 'finance.giving.fundraising', name: 'Manage Fundraising Campaigns', description: 'Create and monitor targeted fundraising drives' },
      { id: 'finance.giving.reports', name: 'View Giving Reports', description: 'Generate donor statements and annual giving summaries' },
      { id: 'finance.income.view', name: 'View Income Directory', description: 'Browse all revenue and income transaction logs' },
      { id: 'finance.income.create', name: 'Record Income Transaction', description: 'Enter new income receipts and revenue entries' },
      { id: 'finance.income.edit', name: 'Edit Income Records', description: 'Modify and update income transactions' },
      { id: 'finance.income.delete', name: 'Delete Income Records', description: 'Remove void or duplicate income entries' },
      { id: 'finance.income.categories', name: 'Manage Income Categories', description: 'Configure revenue stream categories' },
      { id: 'finance.income.reports', name: 'View Income Reports', description: 'Analyze revenue sources and income trends' },
      { id: 'finance.expenses.view', name: 'View Expenses Directory', description: 'Browse all ministry expenditures and bills' },
      { id: 'finance.expenses.create', name: 'Record Expense Transaction', description: 'Log expenditures, vendor receipts, and payment vouchers' },
      { id: 'finance.expenses.edit', name: 'Edit Expense Records', description: 'Modify expense transactions and attachments' },
      { id: 'finance.expenses.delete', name: 'Delete Expense Records', description: 'Remove void expense records' },
      { id: 'finance.expenses.categories', name: 'Manage Expense Categories', description: 'Configure chart of expenditure accounts' },
      { id: 'finance.expenses.reports', name: 'View Expense Reports', description: 'Analyze ministry spending vs category allocations' },
      { id: 'finance.tithes.view', name: 'View Tithes & Offerings', description: 'Inspect tithe records and member tithing status' },
      { id: 'finance.tithes.create', name: 'Record Tithes & Offerings', description: 'Record individual member tithing contributions' },
      { id: 'finance.tithes.edit', name: 'Edit Tithes Records', description: 'Modify recorded tithe amounts and dates' },
      { id: 'finance.tithes.delete', name: 'Delete Tithes Records', description: 'Remove invalid tithe entries' },
      { id: 'finance.tithes.categories', name: 'Manage Tithe Categories', description: 'Configure tithe and offering designations' },
      { id: 'finance.tithes.reports', name: 'View Tithes Reports', description: 'Generate tithing consistency and growth reports' },
      { id: 'finance.budgets.view', name: 'View Budgets Directory', description: 'Browse active and historical fiscal budgets' },
      { id: 'finance.budgets.create', name: 'Create New Budget Plan', description: 'Draft annual or ministry-specific budgets' },
      { id: 'finance.budgets.edit', name: 'Modify Budget Plans', description: 'Update budget targets and line item amounts' },
      { id: 'finance.budgets.delete', name: 'Delete Budget Plans', description: 'Remove archived or draft budgets' },
      { id: 'finance.budgets.categories', name: 'Manage Budget Categories', description: 'Configure budget line items and groupings' },
      { id: 'finance.budgets.allocations', name: 'Manage Budget Allocations', description: 'Distribute funds to departments and branches' },
      { id: 'finance.budgets.reports', name: 'View Budget Reports', description: 'Analyze budget vs actual variance reports' },
      { id: 'finance.reports.view', name: 'Access Financial Reports Hub', description: 'Access unified financial reporting center' },
      { id: 'finance.reports.assets', name: 'View Asset Valuation Reports', description: 'Inspect asset valuation and financial depreciation' },
      { id: 'finance.reports.comparisons', name: 'Comparative Financial Analysis', description: 'Compare quarterly and year-over-year financials' },
      { id: 'finance.export', name: 'Export Financial Data', description: 'Export balance sheets, ledgers, and transactions' },
    ]
  },
  {
    id: 'assets',
    name: 'Assets & Inventory Management',
    description: 'Church equipment, property, valuations, and asset reports',
    permissions: [
      { id: 'assets.view', name: 'View Asset Inventory', description: 'Browse registered church assets, equipment, and details' },
      { id: 'assets.create', name: 'Add New Asset', description: 'Register new property, instruments, vehicles, or equipment' },
      { id: 'assets.edit', name: 'Edit Asset Details', description: 'Update asset location, condition, serial number, and valuation' },
      { id: 'assets.delete', name: 'Delete Asset Records', description: 'Decommission and remove disposed assets' },
      { id: 'assets.categories', name: 'Manage Asset Categories', description: 'Configure equipment and property classifications' },
      { id: 'assets.assignment', name: 'Manage Asset Custodians', description: 'Assign assets to departments, leaders, and custodians' },
      { id: 'assets.maintenance', name: 'Manage Maintenance Logs', description: 'Record maintenance schedules, repairs, and service histories' },
      { id: 'assets.reports', name: 'View Asset Reports', description: 'Generate asset valuation and maintenance reports' },
      { id: 'assets.export', name: 'Export Asset Inventory', description: 'Export asset inventory to CSV or Excel' },
    ]
  },
  {
    id: 'communications',
    name: 'Communications & Messaging',
    description: 'SMS broadcasts, email campaigns, announcements, and newsletters',
    permissions: [
      { id: 'communications.view', name: 'View Communications Hub', description: 'Access messaging dashboard and delivery metrics' },
      { id: 'communications.messages', name: 'Direct Messages', description: 'Send and manage direct SMS/email communications to members' },
      { id: 'communications.campaigns', name: 'Manage Campaigns', description: 'Create, schedule, and run multi-channel campaigns' },
      { id: 'communications.announcements', name: 'Manage Announcements', description: 'Publish church-wide bulletins, notices, and banners' },
      { id: 'communications.newsletters', name: 'Manage Newsletters', description: 'Design and dispatch periodic email newsletters' },
      { id: 'communications.templates', name: 'Manage Message Templates', description: 'Create and edit reusable SMS and email templates' },
      { id: 'communications.send', name: 'Send Mass Broadcasts', description: 'Execute mass SMS and email dispatches to branches or groups' },
    ]
  },
  {
    id: 'settings',
    name: 'Settings & System Administration',
    description: 'Church profile, branches, users, roles, permissions, and backups',
    permissions: [
      { id: 'settings.view', name: 'View General Settings', description: 'Access settings overview and general configurations' },
      { id: 'settings.church-profile', name: 'Manage Church Profile', description: 'Update church branding, logo, address, and contact details' },
      { id: 'settings.branches.view', name: 'View Branch Directory', description: 'Browse church campuses and satellite branches' },
      { id: 'settings.branches.create', name: 'Create New Branch', description: 'Add new campus or satellite branch location' },
      { id: 'settings.branches.edit', name: 'Edit Branch Details', description: 'Modify campus address, pastor in charge, and details' },
      { id: 'settings.branches.delete', name: 'Delete Branch Locations', description: 'Remove branch locations from the system' },
      { id: 'settings.users.view', name: 'View System Users', description: 'Browse registered system users, staff, and operators' },
      { id: 'settings.users.create', name: 'Create System User', description: 'Add new staff and operator user logins' },
      { id: 'settings.users.edit', name: 'Edit User Accounts', description: 'Modify user assignments, emails, and assigned roles' },
      { id: 'settings.users.delete', name: 'Delete User Accounts', description: 'Permanently remove system user accounts' },
      { id: 'settings.users.suspend', name: 'Suspend & Activate Users', description: 'Toggle user account activation status' },
      { id: 'settings.roles.view', name: 'View System Roles', description: 'Browse defined access roles and authority levels' },
      { id: 'settings.roles.create', name: 'Create System Role', description: 'Define custom access roles and privilege bundles' },
      { id: 'settings.roles.edit', name: 'Edit Role & Permissions', description: 'Modify permissions assigned to system roles' },
      { id: 'settings.roles.delete', name: 'Delete System Roles', description: 'Remove custom access roles' },
      { id: 'settings.permissions.manage', name: 'Configure Permissions Matrix', description: 'Access full system-wide permissions matrix and role assignment' },
      { id: 'settings.notifications', name: 'Manage Notification Settings', description: 'Configure automated email and SMS notification triggers' },
      { id: 'settings.integrations', name: 'Manage System Integrations', description: 'Configure payment gateways, email/SMS APIs, and storage' },
      { id: 'settings.backup', name: 'Manage Database Backups', description: 'Create, schedule, and restore system backups' },
      { id: 'settings.system', name: 'System Configuration', description: 'Manage environment parameters and global preferences' },
    ]
  },
  {
    id: 'profile',
    name: 'User Profile & Account',
    description: 'Personal profile, credentials, security, and active sessions',
    permissions: [
      { id: 'profile.view', name: 'View Personal Profile', description: 'View personal user account details and activity history' },
      { id: 'profile.edit', name: 'Edit Personal Profile', description: 'Update personal avatar, phone number, and preferences' },
      { id: 'profile.security', name: 'Manage Account Security', description: 'Update password, enable 2FA, and inspect active sessions' },
    ]
  },
];
