"""Canonical RBAC registry, transcribed from the authoritative frontend source.

``lib/authorization/permissions.ts`` and ``lib/authorization/roles.ts`` are the
single source of truth for the role and permission taxonomies (ADR-003). This
module is their verbatim Python transcription -- it defines no role, permission
or naming scheme of its own.

Generated by ``scripts/generate_rbac_registry.py``; do not hand-edit.
``tests/unit/test_rbac_registry.py`` re-parses both TypeScript files and fails
if this module has drifted from them, so the two taxonomies cannot silently
diverge.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Final


@dataclass(frozen=True, slots=True)
class CanonicalPermission:
    """One permission from ``PERMISSION_CATEGORIES``. ``code`` is its ``id``."""

    code: str
    name: str
    description: str


@dataclass(frozen=True, slots=True)
class CanonicalPermissionCategory:
    """One grouping from ``PERMISSION_CATEGORIES``. ``key`` is its ``id``."""

    key: str
    name: str
    description: str
    permissions: tuple[CanonicalPermission, ...]


@dataclass(frozen=True, slots=True)
class CanonicalRole:
    """One of the six roles in ``ROLES``.

    ``key`` is the ``ROLES`` value verbatim (``SuperAdmin``, ...), which is also
    what ``ROLE_PERMISSIONS`` is keyed by and what the frontend compares against
    in ``lib/authorization/policies.ts``. The canonical source gives roles no
    description, so none is invented here.
    """

    key: str
    name: str


PERMISSION_CATEGORIES: Final[tuple[CanonicalPermissionCategory, ...]] = (
    CanonicalPermissionCategory(
        key="dashboard",
        name="Dashboard & Analytics",
        description="Dashboard metrics, visual charts, custom reports, and analytics preferences",
        permissions=(
            CanonicalPermission(
                code="dashboard.view",
                name="View Main Dashboard",
                description="Access main dashboard overview, metrics, and quick action cards",
            ),
            CanonicalPermission(
                code="analytics.view",
                name="View Analytics Dashboard",
                description="Access high-level analytics, growth trends, and KPI summaries",
            ),
            CanonicalPermission(
                code="analytics.attendance",
                name="View Attendance Analytics",
                description="Access detailed attendance statistics and service comparison charts",
            ),
            CanonicalPermission(
                code="analytics.finance",
                name="View Financial Analytics",
                description="Access giving, revenue, and expense analytic trends",
            ),
            CanonicalPermission(
                code="analytics.demographics",
                name="View Demographics Analytics",
                description="Access member age, gender, and regional distribution insights",
            ),
            CanonicalPermission(
                code="analytics.report-builder",
                name="Custom Report Builder",
                description=(
                    "Build and customize custom analytics reports with metrics and filters"
                ),
            ),
            CanonicalPermission(
                code="analytics.preferences",
                name="Manage Analytics Preferences",
                description=(
                    "Configure custom analytics filters, dashboard widgets, and view settings"
                ),
            ),
            CanonicalPermission(
                code="analytics.export",
                name="Export Analytics Data",
                description="Export charts, analytics metrics, and summary data files",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="activity-logs",
        name="Activity & Audit Logs",
        description="System audit trails, user access history, and event logs",
        permissions=(
            CanonicalPermission(
                code="activity-logs.view",
                name="View Activity Logs Directory",
                description=(
                    "View system audit trails, user logins, and operational action records"
                ),
            ),
            CanonicalPermission(
                code="activity-logs.user",
                name="View User Specific Logs",
                description=(
                    "Inspect detailed audit logs and activity history for individual users"
                ),
            ),
            CanonicalPermission(
                code="activity-logs.filter",
                name="Filter & Search Logs",
                description="Search logs by module, user, date range, IP address, and action type",
            ),
            CanonicalPermission(
                code="activity-logs.export",
                name="Export Activity Logs",
                description="Export audit logs to CSV, Excel, or PDF format",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="members",
        name="Members & Converts Management",
        description="Member directory, profiles, families, converts, and records",
        permissions=(
            CanonicalPermission(
                code="members.view",
                name="View Members Directory",
                description="View members list and detailed profiles",
            ),
            CanonicalPermission(
                code="members.create",
                name="Add New Member & Convert",
                description="Register and create new member records or new converts",
            ),
            CanonicalPermission(
                code="members.edit",
                name="Edit Member Details",
                description="Update member profiles, contact, church details, and personal info",
            ),
            CanonicalPermission(
                code="members.delete",
                name="Delete Member Records",
                description="Remove member and convert records from the system",
            ),
            CanonicalPermission(
                code="members.import",
                name="Import Members",
                description="Bulk import member records from CSV or spreadsheet files",
            ),
            CanonicalPermission(
                code="members.export",
                name="Export Members",
                description="Export member directory lists and datasets to CSV/Excel",
            ),
            CanonicalPermission(
                code="members.contact",
                name="View Confidential Contact Info",
                description="Access phone numbers, physical residences, and personal contact info",
            ),
            CanonicalPermission(
                code="members.converts",
                name="Manage Converts & Follow-ups",
                description=(
                    "Track new converts, assign follow-up mentors, and update milestone stages"
                ),
            ),
            CanonicalPermission(
                code="members.family",
                name="Manage Family Ties",
                description=(
                    "View family relationships, add relatives, and link members to families"
                ),
            ),
            CanonicalPermission(
                code="members.documents",
                name="Manage Member Documents",
                description="Upload and view membership certificates, IDs, and baptism files",
            ),
            CanonicalPermission(
                code="members.giving",
                name="View Member Giving History",
                description="Access individual member contribution and tithing statements",
            ),
            CanonicalPermission(
                code="members.history",
                name="View Member Activity Timeline",
                description=(
                    "Inspect individual member milestone, attendance, and activity timelines"
                ),
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="attendance",
        name="Attendance Management",
        description="Service attendance tracking, QR check-ins, and reports",
        permissions=(
            CanonicalPermission(
                code="attendance.view",
                name="View Attendance Dashboard",
                description="View attendance overviews, summary cards, and stats",
            ),
            CanonicalPermission(
                code="attendance.take",
                name="Take Service Attendance",
                description="Mark headcounts and individual attendance for services",
            ),
            CanonicalPermission(
                code="attendance.qr",
                name="QR Code Check-in & Kiosk",
                description="Use live QR scanner and self-check-in kiosk functionality",
            ),
            CanonicalPermission(
                code="attendance.history",
                name="View Attendance History",
                description="Browse and inspect past service attendance sessions",
            ),
            CanonicalPermission(
                code="attendance.reports",
                name="View Attendance Reports",
                description="Generate and analyze attendance trend reports",
            ),
            CanonicalPermission(
                code="attendance.groups",
                name="Group Attendance",
                description="Record and monitor attendance across small groups and fellowships",
            ),
            CanonicalPermission(
                code="attendance.department",
                name="Department Attendance",
                description="Track departmental and ministry volunteer attendance records",
            ),
            CanonicalPermission(
                code="attendance.member",
                name="Member Attendance Records",
                description="Inspect individual member attendance logs and history",
            ),
            CanonicalPermission(
                code="attendance.edit",
                name="Edit Attendance Records",
                description="Modify and correct recorded attendance numbers",
            ),
            CanonicalPermission(
                code="attendance.delete",
                name="Delete Attendance Records",
                description="Remove mistaken attendance session records",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="groups",
        name="Groups & Ministries",
        description="Small groups, fellowships, group members, and events",
        permissions=(
            CanonicalPermission(
                code="groups.view",
                name="View Groups Directory",
                description="Browse active small groups, fellowships, and group profiles",
            ),
            CanonicalPermission(
                code="groups.create",
                name="Create New Group",
                description="Add new groups, fellowships, cells, or ministry fellowships",
            ),
            CanonicalPermission(
                code="groups.edit",
                name="Edit Group Information",
                description="Modify group descriptions, schedules, meeting points, and locations",
            ),
            CanonicalPermission(
                code="groups.delete",
                name="Delete Groups",
                description="Disband and remove groups from the system",
            ),
            CanonicalPermission(
                code="groups.categories",
                name="Manage Group Categories",
                description="Create and edit group classifications, types, and tags",
            ),
            CanonicalPermission(
                code="groups.members",
                name="Manage Group Members",
                description="Add, transfer, and remove members from groups",
            ),
            CanonicalPermission(
                code="groups.events",
                name="Manage Group Events",
                description="Create and organize group-specific events and meetings",
            ),
            CanonicalPermission(
                code="groups.roles",
                name="Assign Group Roles",
                description="Designate group leaders, assistants, facilitators, and hosts",
            ),
            CanonicalPermission(
                code="groups.attendance",
                name="Track Group Attendance",
                description="Record attendance for small group meetings",
            ),
            CanonicalPermission(
                code="groups.reports",
                name="View Group Reports",
                description="Generate health and attendance reports for small groups",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="departments",
        name="Departments Management",
        description="Church departments, staff, leadership, and meetings",
        permissions=(
            CanonicalPermission(
                code="departments.view",
                name="View Departments",
                description="Browse church departments and ministry teams",
            ),
            CanonicalPermission(
                code="departments.create",
                name="Create Department",
                description="Establish new church departments",
            ),
            CanonicalPermission(
                code="departments.edit",
                name="Edit Department Information",
                description="Update department goals, budgets, and descriptions",
            ),
            CanonicalPermission(
                code="departments.delete",
                name="Delete Departments",
                description="Remove inactive departments",
            ),
            CanonicalPermission(
                code="departments.categories",
                name="Manage Department Categories",
                description="Configure department classifications and structures",
            ),
            CanonicalPermission(
                code="departments.members",
                name="Manage Department Members",
                description="Assign volunteers and staff to departments",
            ),
            CanonicalPermission(
                code="departments.roles",
                name="Manage Department Roles",
                description="Designate department heads, coordinators, and roles",
            ),
            CanonicalPermission(
                code="departments.meetings",
                name="Manage Department Meetings",
                description="Schedule and manage department meetings and minutes",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="sunday-school",
        name="Sunday School Management",
        description="Classes, student records, teacher assignments, and materials",
        permissions=(
            CanonicalPermission(
                code="sunday-school.view",
                name="View Sunday School Dashboard",
                description="Access Sunday school overview and class statistics",
            ),
            CanonicalPermission(
                code="sunday-school.classes.view",
                name="View Classes Directory",
                description="Browse active Sunday school classes and details",
            ),
            CanonicalPermission(
                code="sunday-school.classes.create",
                name="Create New Class",
                description="Add new age brackets, classes, and departments",
            ),
            CanonicalPermission(
                code="sunday-school.classes.edit",
                name="Edit Class Details",
                description="Modify class age brackets, rooms, and descriptions",
            ),
            CanonicalPermission(
                code="sunday-school.classes.delete",
                name="Delete Classes",
                description="Remove Sunday school classes",
            ),
            CanonicalPermission(
                code="sunday-school.students.view",
                name="View Students Directory",
                description="View enrolled Sunday school students and profiles",
            ),
            CanonicalPermission(
                code="sunday-school.students.manage",
                name="Manage Student Enrolment",
                description="Enroll, promote, and transfer students between classes",
            ),
            CanonicalPermission(
                code="sunday-school.teachers.view",
                name="View Teachers Directory",
                description="View Sunday school teacher roster and profiles",
            ),
            CanonicalPermission(
                code="sunday-school.teachers.manage",
                name="Assign & Manage Teachers",
                description="Assign teachers and assistants to classes",
            ),
            CanonicalPermission(
                code="sunday-school.materials.view",
                name="Browse Teaching Materials",
                description="Access curriculum, worksheets, lessons, and digital resources",
            ),
            CanonicalPermission(
                code="sunday-school.materials.manage",
                name="Upload & Manage Materials",
                description="Upload and organize teaching materials and guides",
            ),
            CanonicalPermission(
                code="sunday-school.attendance",
                name="Record Class Attendance",
                description="Take Sunday school attendance per class session",
            ),
            CanonicalPermission(
                code="sunday-school.reports",
                name="View Sunday School Reports",
                description="Generate Sunday school growth and attendance reports",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="prayer-requests",
        name="Prayer Requests Management",
        description="Prayer request submissions, intercession teams, and confidential notes",
        permissions=(
            CanonicalPermission(
                code="prayer-requests.view",
                name="View Prayer Requests",
                description="Browse and read public prayer requests",
            ),
            CanonicalPermission(
                code="prayer-requests.view-confidential",
                name="View Confidential Requests",
                description="Access private, sensitive, and pastoral prayer requests",
            ),
            CanonicalPermission(
                code="prayer-requests.create",
                name="Submit Prayer Request",
                description="Create and log new prayer requests",
            ),
            CanonicalPermission(
                code="prayer-requests.edit",
                name="Edit Prayer Requests",
                description="Modify prayer request text and details",
            ),
            CanonicalPermission(
                code="prayer-requests.delete",
                name="Delete Prayer Requests",
                description="Remove resolved or outdated prayer requests",
            ),
            CanonicalPermission(
                code="prayer-requests.respond",
                name="Respond to Requests",
                description="Add encouraging notes, answers to prayer, and updates",
            ),
            CanonicalPermission(
                code="prayer-requests.assign",
                name="Assign to Prayer Team",
                description="Delegate requests to specific intercessors and pastoral teams",
            ),
            CanonicalPermission(
                code="prayer-requests.categories",
                name="Manage Prayer Categories",
                description="Configure prayer request topics and categories",
            ),
            CanonicalPermission(
                code="prayer-requests.status",
                name="Update Request Status",
                description="Mark requests as praying, answered, or archived",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="pastoral-care",
        name="Pastoral Care",
        description="Pastoral cases, counselling sessions, visitations, and follow-up assignments",
        permissions=(
            CanonicalPermission(
                code="pastoral-care.view",
                name="View Pastoral Care",
                description="Access the pastoral care dashboard, cases, and visitation records",
            ),
            CanonicalPermission(
                code="pastoral-care.manage",
                name="Manage Pastoral Care",
                description=(
                    "Create and update pastoral cases, sessions, assignments, and follow-ups"
                ),
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="events",
        name="Events Management",
        description="Church events, calendar, registrations, templates, and export",
        permissions=(
            CanonicalPermission(
                code="events.view",
                name="View Events Directory",
                description="Browse all upcoming and past church events and profiles",
            ),
            CanonicalPermission(
                code="events.create",
                name="Create New Event",
                description="Schedule and publish new church events",
            ),
            CanonicalPermission(
                code="events.edit",
                name="Edit Event Details",
                description="Modify dates, locations, speakers, banners, and event info",
            ),
            CanonicalPermission(
                code="events.delete",
                name="Delete Events",
                description="Cancel and delete events",
            ),
            CanonicalPermission(
                code="events.calendar",
                name="View Event Calendar",
                description="Access interactive monthly, weekly, and daily event calendars",
            ),
            CanonicalPermission(
                code="events.categories",
                name="Manage Event Categories",
                description="Configure event categories, departments, and color tags",
            ),
            CanonicalPermission(
                code="events.templates",
                name="Manage Event Templates",
                description="Create and reuse event scheduling templates",
            ),
            CanonicalPermission(
                code="events.registrations",
                name="Manage Event Registrations",
                description="Track RSVPs, tickets, and attendee registrations",
            ),
            CanonicalPermission(
                code="events.attendance",
                name="Track Event Attendance",
                description="Check-in attendees at event entrances",
            ),
            CanonicalPermission(
                code="events.groups",
                name="Manage Group Event Linkings",
                description="Coordinate small group and ministry participation in events",
            ),
            CanonicalPermission(
                code="events.bulk",
                name="Execute Bulk Actions",
                description="Perform bulk status updates and attendee notifications",
            ),
            CanonicalPermission(
                code="events.export",
                name="Export Events Data",
                description="Export event rosters and calendar datasets",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="finance",
        name="Finance Management",
        description="Giving, donations, income, expenses, tithes, budgets, and statements",
        permissions=(
            CanonicalPermission(
                code="finance.view",
                name="View Finance Overview",
                description="Access finance dashboard summaries and quick financial stats",
            ),
            CanonicalPermission(
                code="finance.giving.view",
                name="View Giving & Donations",
                description="Browse giving transactions, donations, and donor records",
            ),
            CanonicalPermission(
                code="finance.giving.manage",
                name="Record Congregational Giving",
                description="Record Sunday service offering collections",
            ),
            CanonicalPermission(
                code="finance.giving.categories",
                name="Manage Giving Categories",
                description="Configure funds, special appeals, and giving categories",
            ),
            CanonicalPermission(
                code="finance.giving.donations",
                name="Manage Donations",
                description="Log and edit general donations and donor receipts",
            ),
            CanonicalPermission(
                code="finance.giving.pledges",
                name="Manage Pledges",
                description="Track building fund pledges and fulfillment status",
            ),
            CanonicalPermission(
                code="finance.giving.fundraising",
                name="Manage Fundraising Campaigns",
                description="Create and monitor targeted fundraising drives",
            ),
            CanonicalPermission(
                code="finance.giving.reports",
                name="View Giving Reports",
                description="Generate donor statements and annual giving summaries",
            ),
            CanonicalPermission(
                code="finance.income.view",
                name="View Income Directory",
                description="Browse all revenue and income transaction logs",
            ),
            CanonicalPermission(
                code="finance.income.create",
                name="Record Income Transaction",
                description="Enter new income receipts and revenue entries",
            ),
            CanonicalPermission(
                code="finance.income.edit",
                name="Edit Income Records",
                description="Modify and update income transactions",
            ),
            CanonicalPermission(
                code="finance.income.delete",
                name="Delete Income Records",
                description="Remove void or duplicate income entries",
            ),
            CanonicalPermission(
                code="finance.income.categories",
                name="Manage Income Categories",
                description="Configure revenue stream categories",
            ),
            CanonicalPermission(
                code="finance.income.reports",
                name="View Income Reports",
                description="Analyze revenue sources and income trends",
            ),
            CanonicalPermission(
                code="finance.expenses.view",
                name="View Expenses Directory",
                description="Browse all ministry expenditures and bills",
            ),
            CanonicalPermission(
                code="finance.expenses.create",
                name="Record Expense Transaction",
                description="Log expenditures, vendor receipts, and payment vouchers",
            ),
            CanonicalPermission(
                code="finance.expenses.edit",
                name="Edit Expense Records",
                description="Modify expense transactions and attachments",
            ),
            CanonicalPermission(
                code="finance.expenses.delete",
                name="Delete Expense Records",
                description="Remove void expense records",
            ),
            CanonicalPermission(
                code="finance.expenses.categories",
                name="Manage Expense Categories",
                description="Configure chart of expenditure accounts",
            ),
            CanonicalPermission(
                code="finance.expenses.reports",
                name="View Expense Reports",
                description="Analyze ministry spending vs category allocations",
            ),
            CanonicalPermission(
                code="finance.tithes.view",
                name="View Tithes & Offerings",
                description="Inspect tithe records and member tithing status",
            ),
            CanonicalPermission(
                code="finance.tithes.create",
                name="Record Tithes & Offerings",
                description="Record individual member tithing contributions",
            ),
            CanonicalPermission(
                code="finance.tithes.edit",
                name="Edit Tithes Records",
                description="Modify recorded tithe amounts and dates",
            ),
            CanonicalPermission(
                code="finance.tithes.delete",
                name="Delete Tithes Records",
                description="Remove invalid tithe entries",
            ),
            CanonicalPermission(
                code="finance.tithes.categories",
                name="Manage Tithe Categories",
                description="Configure tithe and offering designations",
            ),
            CanonicalPermission(
                code="finance.tithes.reports",
                name="View Tithes Reports",
                description="Generate tithing consistency and growth reports",
            ),
            CanonicalPermission(
                code="finance.budgets.view",
                name="View Budgets Directory",
                description="Browse active and historical fiscal budgets",
            ),
            CanonicalPermission(
                code="finance.budgets.create",
                name="Create New Budget Plan",
                description="Draft annual or ministry-specific budgets",
            ),
            CanonicalPermission(
                code="finance.budgets.edit",
                name="Modify Budget Plans",
                description="Update budget targets and line item amounts",
            ),
            CanonicalPermission(
                code="finance.budgets.delete",
                name="Delete Budget Plans",
                description="Remove archived or draft budgets",
            ),
            CanonicalPermission(
                code="finance.budgets.categories",
                name="Manage Budget Categories",
                description="Configure budget line items and groupings",
            ),
            CanonicalPermission(
                code="finance.budgets.allocations",
                name="Manage Budget Allocations",
                description="Distribute funds to departments and branches",
            ),
            CanonicalPermission(
                code="finance.budgets.reports",
                name="View Budget Reports",
                description="Analyze budget vs actual variance reports",
            ),
            CanonicalPermission(
                code="finance.reports.view",
                name="Access Financial Reports Hub",
                description="Access unified financial reporting center",
            ),
            CanonicalPermission(
                code="finance.reports.assets",
                name="View Asset Valuation Reports",
                description="Inspect asset valuation and financial depreciation",
            ),
            CanonicalPermission(
                code="finance.reports.comparisons",
                name="Comparative Financial Analysis",
                description="Compare quarterly and year-over-year financials",
            ),
            CanonicalPermission(
                code="finance.export",
                name="Export Financial Data",
                description="Export balance sheets, ledgers, and transactions",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="assets",
        name="Assets & Inventory Management",
        description="Church equipment, property, valuations, and asset reports",
        permissions=(
            CanonicalPermission(
                code="assets.view",
                name="View Asset Inventory",
                description="Browse registered church assets, equipment, and details",
            ),
            CanonicalPermission(
                code="assets.create",
                name="Add New Asset",
                description="Register new property, instruments, vehicles, or equipment",
            ),
            CanonicalPermission(
                code="assets.edit",
                name="Edit Asset Details",
                description="Update asset location, condition, serial number, and valuation",
            ),
            CanonicalPermission(
                code="assets.delete",
                name="Delete Asset Records",
                description="Decommission and remove disposed assets",
            ),
            CanonicalPermission(
                code="assets.categories",
                name="Manage Asset Categories",
                description="Configure equipment and property classifications",
            ),
            CanonicalPermission(
                code="assets.assignment",
                name="Manage Asset Custodians",
                description="Assign assets to departments, leaders, and custodians",
            ),
            CanonicalPermission(
                code="assets.maintenance",
                name="Manage Maintenance Logs",
                description="Record maintenance schedules, repairs, and service histories",
            ),
            CanonicalPermission(
                code="assets.reports",
                name="View Asset Reports",
                description="Generate asset valuation and maintenance reports",
            ),
            CanonicalPermission(
                code="assets.export",
                name="Export Asset Inventory",
                description="Export asset inventory to CSV or Excel",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="communications",
        name="Communications & Messaging",
        description="SMS broadcasts, email campaigns, announcements, and newsletters",
        permissions=(
            CanonicalPermission(
                code="communications.view",
                name="View Communications Hub",
                description="Access messaging dashboard and delivery metrics",
            ),
            CanonicalPermission(
                code="communications.messages",
                name="Direct Messages",
                description="Send and manage direct SMS/email communications to members",
            ),
            CanonicalPermission(
                code="communications.campaigns",
                name="Manage Campaigns",
                description="Create, schedule, and run multi-channel campaigns",
            ),
            CanonicalPermission(
                code="communications.announcements",
                name="Manage Announcements",
                description="Publish church-wide bulletins, notices, and banners",
            ),
            CanonicalPermission(
                code="communications.newsletters",
                name="Manage Newsletters",
                description="Design and dispatch periodic email newsletters",
            ),
            CanonicalPermission(
                code="communications.templates",
                name="Manage Message Templates",
                description="Create and edit reusable SMS and email templates",
            ),
            CanonicalPermission(
                code="communications.send",
                name="Send Mass Broadcasts",
                description="Execute mass SMS and email dispatches to branches or groups",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="settings",
        name="Settings & System Administration",
        description="Church profile, branches, users, roles, permissions, and backups",
        permissions=(
            CanonicalPermission(
                code="settings.view",
                name="View General Settings",
                description="Access settings overview and general configurations",
            ),
            CanonicalPermission(
                code="settings.church-profile",
                name="Manage Church Profile",
                description="Update church branding, logo, address, and contact details",
            ),
            CanonicalPermission(
                code="settings.branches.view",
                name="View Branch Directory",
                description="Browse church branches and satellite locations",
            ),
            CanonicalPermission(
                code="settings.branches.create",
                name="Create New Branch",
                description="Add new church branch or satellite location",
            ),
            CanonicalPermission(
                code="settings.branches.edit",
                name="Edit Branch Details",
                description="Modify branch address, pastor in charge, and details",
            ),
            CanonicalPermission(
                code="settings.branches.delete",
                name="Delete Branch Locations",
                description="Remove branch locations from the system",
            ),
            CanonicalPermission(
                code="settings.users.view",
                name="View System Users",
                description="Browse registered system users, staff, and operators",
            ),
            CanonicalPermission(
                code="settings.users.create",
                name="Create System User",
                description="Add new staff and operator user logins",
            ),
            CanonicalPermission(
                code="settings.users.edit",
                name="Edit User Accounts",
                description="Modify user assignments, emails, and assigned roles",
            ),
            CanonicalPermission(
                code="settings.users.delete",
                name="Delete User Accounts",
                description="Permanently remove system user accounts",
            ),
            CanonicalPermission(
                code="settings.users.suspend",
                name="Suspend & Activate Users",
                description="Toggle user account activation status",
            ),
            CanonicalPermission(
                code="settings.roles.view",
                name="View System Roles",
                description="Browse defined access roles and authority levels",
            ),
            CanonicalPermission(
                code="settings.roles.create",
                name="Create System Role",
                description="Define custom access roles and privilege bundles",
            ),
            CanonicalPermission(
                code="settings.roles.edit",
                name="Edit Role & Permissions",
                description="Modify permissions assigned to system roles",
            ),
            CanonicalPermission(
                code="settings.roles.delete",
                name="Delete System Roles",
                description="Remove custom access roles",
            ),
            CanonicalPermission(
                code="settings.permissions.manage",
                name="Configure Permissions Matrix",
                description="Access full system-wide permissions matrix and role assignment",
            ),
            CanonicalPermission(
                code="settings.notifications",
                name="Manage Notification Settings",
                description="Configure automated email and SMS notification triggers",
            ),
            CanonicalPermission(
                code="settings.integrations",
                name="Manage System Integrations",
                description="Configure payment gateways, email/SMS APIs, and storage",
            ),
            CanonicalPermission(
                code="settings.backup",
                name="Manage Database Backups",
                description="Create, schedule, and restore system backups",
            ),
            CanonicalPermission(
                code="settings.system",
                name="System Configuration",
                description="Manage environment parameters and global preferences",
            ),
        ),
    ),
    CanonicalPermissionCategory(
        key="profile",
        name="User Profile & Account",
        description="Personal profile, credentials, security, and active sessions",
        permissions=(
            CanonicalPermission(
                code="profile.view",
                name="View Personal Profile",
                description="View personal user account details and activity history",
            ),
            CanonicalPermission(
                code="profile.edit",
                name="Edit Personal Profile",
                description="Update personal avatar, phone number, and preferences",
            ),
            CanonicalPermission(
                code="profile.security",
                name="Manage Account Security",
                description="Update password, enable 2FA, and inspect active sessions",
            ),
        ),
    ),
)

CATEGORISED_PERMISSION_CODES: Final[tuple[str, ...]] = tuple(
    permission.code for category in PERMISSION_CATEGORIES for permission in category.permissions
)
"""Codes reachable through ``PERMISSION_CATEGORIES``, in declaration order."""

UNCATEGORISED_PERMISSION_CODES: Final[tuple[str, ...]] = ()
"""Codes the flat ``PERMISSIONS`` const defines but that no category lists.

Empty while the two lists agree, which is the intended state: a code here
is granted by ``ROLE_PERMISSIONS`` yet invisible to
``ROLE_PERMISSIONS[SuperAdmin]``, which is computed by flattening the
categories -- so SuperAdmin would lack a permission that lesser roles hold.
Such codes are still seeded, with name, description and category NULL rather
than invented text, so the gap is visible in the data. See ADR-009.
"""

PERMISSION_CODES: Final[tuple[str, ...]] = (
    *CATEGORISED_PERMISSION_CODES,
    *UNCATEGORISED_PERMISSION_CODES,
)
"""Every canonical code: the union the ``permissions`` table is seeded from."""

CANONICAL_ROLES: Final[tuple[CanonicalRole, ...]] = (
    CanonicalRole(key="SuperAdmin", name="SuperAdmin"),
    CanonicalRole(key="Admin", name="Admin"),
    CanonicalRole(key="Pastor", name="Pastor"),
    CanonicalRole(key="Accountant", name="Accountant"),
    CanonicalRole(key="Secretary", name="Secretary"),
    CanonicalRole(key="Teacher", name="Teacher"),
)

ROLE_PERMISSIONS: Final[Mapping[str, frozenset[str]]] = MappingProxyType(
    {
        "SuperAdmin": frozenset(
            CATEGORISED_PERMISSION_CODES  # exactly what ROLE_PERMISSIONS computes
        ),
        "Admin": frozenset(
            (
                "dashboard.view",
                "analytics.view",
                "analytics.attendance",
                "analytics.finance",
                "analytics.demographics",
                "analytics.report-builder",
                "analytics.preferences",
                "analytics.export",
                "activity-logs.view",
                "activity-logs.user",
                "activity-logs.filter",
                "activity-logs.export",
                "members.view",
                "members.create",
                "members.edit",
                "members.import",
                "members.export",
                "members.contact",
                "members.converts",
                "members.family",
                "members.documents",
                "members.giving",
                "members.history",
                "attendance.view",
                "attendance.take",
                "attendance.qr",
                "attendance.history",
                "attendance.reports",
                "attendance.groups",
                "attendance.department",
                "attendance.member",
                "attendance.edit",
                "groups.view",
                "groups.create",
                "groups.edit",
                "groups.delete",
                "groups.categories",
                "groups.members",
                "groups.events",
                "groups.roles",
                "groups.attendance",
                "groups.reports",
                "departments.view",
                "departments.create",
                "departments.edit",
                "departments.delete",
                "departments.categories",
                "departments.members",
                "departments.roles",
                "departments.meetings",
                "sunday-school.view",
                "sunday-school.classes.view",
                "sunday-school.classes.create",
                "sunday-school.classes.edit",
                "sunday-school.students.view",
                "sunday-school.students.manage",
                "sunday-school.teachers.view",
                "sunday-school.teachers.manage",
                "sunday-school.materials.view",
                "sunday-school.materials.manage",
                "sunday-school.attendance",
                "sunday-school.reports",
                "prayer-requests.view",
                "prayer-requests.view-confidential",
                "prayer-requests.create",
                "prayer-requests.edit",
                "prayer-requests.delete",
                "prayer-requests.respond",
                "prayer-requests.assign",
                "prayer-requests.categories",
                "prayer-requests.status",
                "pastoral-care.view",
                "pastoral-care.manage",
                "events.view",
                "events.create",
                "events.edit",
                "events.delete",
                "events.calendar",
                "events.categories",
                "events.templates",
                "events.registrations",
                "events.attendance",
                "events.groups",
                "events.bulk",
                "events.export",
                "assets.view",
                "assets.create",
                "assets.edit",
                "assets.delete",
                "assets.categories",
                "assets.assignment",
                "assets.maintenance",
                "assets.reports",
                "assets.export",
                "communications.view",
                "communications.messages",
                "communications.campaigns",
                "communications.announcements",
                "communications.newsletters",
                "communications.templates",
                "communications.send",
                "settings.view",
                "settings.church-profile",
                "settings.branches.view",
                "settings.branches.create",
                "settings.branches.edit",
                "settings.users.view",
                "settings.users.create",
                "settings.users.edit",
                "settings.roles.view",
                "settings.roles.create",
                "settings.roles.edit",
                "settings.notifications",
                "settings.integrations",
                "settings.backup",
                "settings.system",
                "profile.view",
                "profile.edit",
                "profile.security",
            )
        ),
        "Pastor": frozenset(
            (
                "dashboard.view",
                "analytics.view",
                "analytics.attendance",
                "analytics.demographics",
                "analytics.export",
                "members.view",
                "members.create",
                "members.edit",
                "members.contact",
                "members.converts",
                "members.family",
                "members.documents",
                "members.history",
                "attendance.view",
                "attendance.take",
                "attendance.history",
                "attendance.reports",
                "attendance.groups",
                "attendance.department",
                "attendance.member",
                "groups.view",
                "groups.create",
                "groups.edit",
                "groups.members",
                "groups.events",
                "groups.roles",
                "groups.reports",
                "departments.view",
                "departments.members",
                "departments.roles",
                "departments.meetings",
                "sunday-school.view",
                "sunday-school.classes.view",
                "sunday-school.reports",
                "prayer-requests.view",
                "prayer-requests.view-confidential",
                "prayer-requests.create",
                "prayer-requests.edit",
                "prayer-requests.respond",
                "prayer-requests.assign",
                "prayer-requests.categories",
                "prayer-requests.status",
                "pastoral-care.view",
                "pastoral-care.manage",
                "events.view",
                "events.create",
                "events.edit",
                "events.calendar",
                "events.registrations",
                "events.attendance",
                "events.groups",
                "communications.view",
                "communications.messages",
                "communications.campaigns",
                "communications.announcements",
                "communications.newsletters",
                "communications.send",
                "settings.view",
                "settings.branches.view",
                "profile.view",
                "profile.edit",
                "profile.security",
            )
        ),
        "Accountant": frozenset(
            (
                "dashboard.view",
                "analytics.view",
                "analytics.finance",
                "analytics.report-builder",
                "analytics.export",
                "finance.view",
                "finance.giving.view",
                "finance.giving.manage",
                "finance.giving.categories",
                "finance.giving.donations",
                "finance.giving.pledges",
                "finance.giving.fundraising",
                "finance.giving.reports",
                "finance.income.view",
                "finance.income.create",
                "finance.income.edit",
                "finance.income.delete",
                "finance.income.categories",
                "finance.income.reports",
                "finance.expenses.view",
                "finance.expenses.create",
                "finance.expenses.edit",
                "finance.expenses.delete",
                "finance.expenses.categories",
                "finance.expenses.reports",
                "finance.tithes.view",
                "finance.tithes.create",
                "finance.tithes.edit",
                "finance.tithes.delete",
                "finance.tithes.categories",
                "finance.tithes.reports",
                "finance.budgets.view",
                "finance.budgets.create",
                "finance.budgets.edit",
                "finance.budgets.delete",
                "finance.budgets.categories",
                "finance.budgets.allocations",
                "finance.budgets.reports",
                "finance.reports.view",
                "finance.reports.assets",
                "finance.reports.comparisons",
                "finance.export",
                "assets.view",
                "assets.create",
                "assets.edit",
                "assets.reports",
                "assets.export",
                "profile.view",
                "profile.edit",
                "profile.security",
            )
        ),
        "Secretary": frozenset(
            (
                "dashboard.view",
                "members.view",
                "members.create",
                "members.edit",
                "members.import",
                "members.export",
                "members.contact",
                "members.converts",
                "members.family",
                "members.documents",
                "members.history",
                "attendance.view",
                "attendance.take",
                "attendance.qr",
                "attendance.history",
                "attendance.reports",
                "attendance.groups",
                "attendance.department",
                "attendance.member",
                "groups.view",
                "groups.members",
                "groups.events",
                "departments.view",
                "departments.members",
                "departments.meetings",
                "events.view",
                "events.create",
                "events.edit",
                "events.calendar",
                "events.registrations",
                "events.attendance",
                "events.export",
                "communications.view",
                "communications.messages",
                "communications.announcements",
                "communications.newsletters",
                "communications.templates",
                "communications.send",
                "prayer-requests.view",
                "prayer-requests.create",
                "prayer-requests.status",
                "profile.view",
                "profile.edit",
                "profile.security",
            )
        ),
        "Teacher": frozenset(
            (
                "dashboard.view",
                "sunday-school.view",
                "sunday-school.classes.view",
                "sunday-school.students.view",
                "sunday-school.students.manage",
                "sunday-school.teachers.view",
                "sunday-school.materials.view",
                "sunday-school.materials.manage",
                "sunday-school.attendance",
                "sunday-school.reports",
                "members.view",
                "events.view",
                "events.calendar",
                "profile.view",
                "profile.edit",
                "profile.security",
            )
        ),
    }
)
